#!/usr/bin/env python
from db import Dictionay
import sys

word = '_'.join(sys.argv[1:]).lower()

dic = Dictionay()
meaning = list(dic.get_meaning(word))
meaning = meaning[:min(len(meaning),5)]

if meaning:
    print(meaning[0])
    print('\n'.join(meaning[1:]))
else:
    print('Result Not Found!!!')
dic.close()
